### ISSUE TITLE
Can't build on Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-cpp#68]
See my logs:

```
In file included from casbin/util/built_in_functions.cpp:30:
casbin/util/../ip_parser/parser/parseCIDR.h:14:10: fatal error: ../exception/ParserException.h: No such file or directory
   14 | #include "../exception/ParserException.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

![image](https://user-images.githubusercontent.com/3787410/98215917-58726180-1f83-11eb-8557-8f5f9eaacaa7.png)

Also see Travis CI: https://travis-ci.org/github/casbin/casbin-cpp

**Comment by hsluoyz** [comment]
@xcaptain @divy9881
